name: Expo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7.0.0

      - name: Setup Node
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 26.4.0

      - name: Install Node.js dependencies
        run: npm clean-install

      - name: Run ESLint
        run: npm run lint
